/*
 * This file is generated by jOOQ.
 */
package com.pythongong.community.user.model;


import com.pythongong.community.user.model.tables.CommunityUser;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in user_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COMMUNITY_USER_IDX_USER_TYPE = Internal.createIndex(DSL.name("idx_user_type"), CommunityUser.COMMUNITY_USER, new OrderField[] { CommunityUser.COMMUNITY_USER.USER_TYPE }, false);
}
