/*
 * This file is generated by jOOQ.
 */
package com.pythongong.community.user.model;


import com.pythongong.community.user.model.tables.CommunityUser;
import com.pythongong.community.user.model.tables.records.CommunityUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * user_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommunityUserRecord> KEY_COMMUNITY_USER_PRIMARY = Internal.createUniqueKey(CommunityUser.COMMUNITY_USER, DSL.name("KEY_community_user_PRIMARY"), new TableField[] { CommunityUser.COMMUNITY_USER.ID }, true);
    public static final UniqueKey<CommunityUserRecord> KEY_COMMUNITY_USER_UK_USERNAME = Internal.createUniqueKey(CommunityUser.COMMUNITY_USER, DSL.name("KEY_community_user_uk_username"), new TableField[] { CommunityUser.COMMUNITY_USER.USER_NAME }, true);
}
