/*
 * This file is generated by jOOQ.
 */
package com.pythongong.community.user.model;


import com.pythongong.community.user.model.tables.CommunityUser;


/**
 * Convenience access to all tables in user_management.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Stores information about registered users of the application.
     */
    public static final CommunityUser COMMUNITY_USER = CommunityUser.COMMUNITY_USER;
}
