/*
 * This file is generated by jOOQ.
 */
package com.pythongong.community.user.model;


import com.pythongong.community.user.model.tables.CommunityUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserManagement extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_management</code>
     */
    public static final UserManagement USER_MANAGEMENT = new UserManagement();

    /**
     * Stores information about registered users of the application.
     */
    public final CommunityUser COMMUNITY_USER = CommunityUser.COMMUNITY_USER;

    /**
     * No further instances allowed
     */
    private UserManagement() {
        super("user_management", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CommunityUser.COMMUNITY_USER
        );
    }
}
